var dbits,canary=0xdeadbeefcafe,j_lm=15715070==(canary&16777215);function BigInteger(a,b,c){null!=a&&(null==b&&"string"!=typeof a?this.fromString(a,256):this.fromString(a,b))}function nbi(){return new BigInteger(null)}function am1(a,b,c,d,f,e){for(;0<=--e;){var g=b*this[a++]+c[d]+f;f=Math.floor(g/67108864);c[d++]=g&67108863}return f}
function am2(a,b,c,d,f,e){var g=b&32767;for(b>>=15;0<=--e;){var h=this[a]&32767,k=this[a++]>>15,l=b*h+k*g,h=g*h+((l&32767)<<15)+c[d]+(f&1073741823);f=(h>>>30)+(l>>>15)+b*k+(f>>>30);c[d++]=h&1073741823}return f}function am3(a,b,c,d,f,e){var g=b&16383;for(b>>=14;0<=--e;){var h=this[a]&16383,k=this[a++]>>14,l=b*h+k*g,h=g*h+((l&16383)<<14)+c[d]+f;f=(h>>28)+(l>>14)+b*k;c[d++]=h&268435455}return f}
j_lm&&"Microsoft Internet Explorer"==navigator.appName?(BigInteger.prototype.am=am2,dbits=30):j_lm&&"Netscape"!=navigator.appName?(BigInteger.prototype.am=am1,dbits=26):(BigInteger.prototype.am=am3,dbits=28);BigInteger.prototype.DB=dbits;BigInteger.prototype.DM=(1<<dbits)-1;BigInteger.prototype.DV=1<<dbits;var BI_FP=52;BigInteger.prototype.FV=Math.pow(2,BI_FP);BigInteger.prototype.F1=BI_FP-dbits;BigInteger.prototype.F2=2*dbits-BI_FP;var BI_RM="0123456789abcdefghijklmnopqrstuvwxyz",BI_RC=[],rr,vv;
rr=48;for(vv=0;9>=vv;++vv)BI_RC[rr++]=vv;rr=97;for(vv=10;36>vv;++vv)BI_RC[rr++]=vv;rr=65;for(vv=10;36>vv;++vv)BI_RC[rr++]=vv;function int2char(a){return BI_RM.charAt(a)}function intAt(a,b){var c=BI_RC[a.charCodeAt(b)];return null==c?-1:c}function bnpCopyTo(a){for(var b=this.t-1;0<=b;--b)a[b]=this[b];a.t=this.t;a.s=this.s}function bnpFromInt(a){this.t=1;this.s=0>a?-1:0;0<a?this[0]=a:-1>a?this[0]=a+this.DV:this.t=0}function nbv(a){var b=nbi();b.fromInt(a);return b}
function bnpFromString(a,b){var c;if(16==b)c=4;else if(8==b)c=3;else if(256==b)c=8;else if(2==b)c=1;else if(32==b)c=5;else if(4==b)c=2;else{this.fromRadix(a,b);return}this.s=this.t=0;for(var d=a.length,f=!1,e=0;0<=--d;){var g=8==c?a[d]&255:intAt(a,d);0>g?"-"==a.charAt(d)&&(f=!0):(f=!1,0==e?this[this.t++]=g:e+c>this.DB?(this[this.t-1]|=(g&(1<<this.DB-e)-1)<<e,this[this.t++]=g>>this.DB-e):this[this.t-1]|=g<<e,e+=c,e>=this.DB&&(e-=this.DB))}8==c&&0!=(a[0]&128)&&(this.s=-1,0<e&&(this[this.t-1]|=(1<<this.DB-
e)-1<<e));this.clamp();f&&BigInteger.ZERO.subTo(this,this)}function bnpClamp(){for(var a=this.s&this.DM;0<this.t&&this[this.t-1]==a;)--this.t}
function bnToString(a){if(0>this.s)return"-"+this.negate().toString(a);if(16==a)a=4;else if(8==a)a=3;else if(2==a)a=1;else if(32==a)a=5;else if(4==a)a=2;else return this.toRadix(a);var b=(1<<a)-1,c,d=!1,f="",e=this.t,g=this.DB-e*this.DB%a;if(0<e--){if(g<this.DB&&0<(c=this[e]>>g))d=!0,f=int2char(c);for(;0<=e;)g<a?(c=(this[e]&(1<<g)-1)<<a-g,c|=this[--e]>>(g+=this.DB-a)):(c=this[e]>>(g-=a)&b,0>=g&&(g+=this.DB,--e)),0<c&&(d=!0),d&&(f+=int2char(c))}return d?f:"0"}
function bnNegate(){var a=nbi();BigInteger.ZERO.subTo(this,a);return a}function bnAbs(){return 0>this.s?this.negate():this}function bnCompareTo(a){var b=this.s-a.s;if(0!=b)return b;var c=this.t,b=c-a.t;if(0!=b)return 0>this.s?-b:b;for(;0<=--c;)if(0!=(b=this[c]-a[c]))return b;return 0}function nbits(a){var b=1,c;if(0!=(c=a>>>16))a=c,b+=16;if(0!=(c=a>>8))a=c,b+=8;if(0!=(c=a>>4))a=c,b+=4;if(0!=(c=a>>2))a=c,b+=2;0!=a>>1&&(b+=1);return b}
function bnBitLength(){return 0>=this.t?0:this.DB*(this.t-1)+nbits(this[this.t-1]^this.s&this.DM)}function bnpDLShiftTo(a,b){var c;for(c=this.t-1;0<=c;--c)b[c+a]=this[c];for(c=a-1;0<=c;--c)b[c]=0;b.t=this.t+a;b.s=this.s}function bnpDRShiftTo(a,b){for(var c=a;c<this.t;++c)b[c-a]=this[c];b.t=Math.max(this.t-a,0);b.s=this.s}
function bnpLShiftTo(a,b){var c=a%this.DB,d=this.DB-c,f=(1<<d)-1,e=Math.floor(a/this.DB),g=this.s<<c&this.DM,h;for(h=this.t-1;0<=h;--h)b[h+e+1]=this[h]>>d|g,g=(this[h]&f)<<c;for(h=e-1;0<=h;--h)b[h]=0;b[e]=g;b.t=this.t+e+1;b.s=this.s;b.clamp()}
function bnpRShiftTo(a,b){b.s=this.s;var c=Math.floor(a/this.DB);if(c>=this.t)b.t=0;else{var d=a%this.DB,f=this.DB-d,e=(1<<d)-1;b[0]=this[c]>>d;for(var g=c+1;g<this.t;++g)b[g-c-1]|=(this[g]&e)<<f,b[g-c]=this[g]>>d;0<d&&(b[this.t-c-1]|=(this.s&e)<<f);b.t=this.t-c;b.clamp()}}
function bnpSubTo(a,b){for(var c=0,d=0,f=Math.min(a.t,this.t);c<f;)d+=this[c]-a[c],b[c++]=d&this.DM,d>>=this.DB;if(a.t<this.t){for(d-=a.s;c<this.t;)d+=this[c],b[c++]=d&this.DM,d>>=this.DB;d+=this.s}else{for(d+=this.s;c<a.t;)d-=a[c],b[c++]=d&this.DM,d>>=this.DB;d-=a.s}b.s=0>d?-1:0;-1>d?b[c++]=this.DV+d:0<d&&(b[c++]=d);b.t=c;b.clamp()}
function bnpMultiplyTo(a,b){var c=this.abs(),d=a.abs(),f=c.t;for(b.t=f+d.t;0<=--f;)b[f]=0;for(f=0;f<d.t;++f)b[f+c.t]=c.am(0,d[f],b,f,0,c.t);b.s=0;b.clamp();this.s!=a.s&&BigInteger.ZERO.subTo(b,b)}function bnpSquareTo(a){for(var b=this.abs(),c=a.t=2*b.t;0<=--c;)a[c]=0;for(c=0;c<b.t-1;++c){var d=b.am(c,b[c],a,2*c,0,1);if((a[c+b.t]+=b.am(c+1,2*b[c],a,2*c+1,d,b.t-c-1))>=b.DV)a[c+b.t]-=b.DV,a[c+b.t+1]=1}0<a.t&&(a[a.t-1]+=b.am(c,b[c],a,2*c,0,1));a.s=0;a.clamp()}
function bnpDivRemTo(a,b,c){var d=a.abs();if(!(0>=d.t)){var f=this.abs();if(f.t<d.t)null!=b&&b.fromInt(0),null!=c&&this.copyTo(c);else{null==c&&(c=nbi());var e=nbi(),g=this.s;a=a.s;var h=this.DB-nbits(d[d.t-1]);0<h?(d.lShiftTo(h,e),f.lShiftTo(h,c)):(d.copyTo(e),f.copyTo(c));d=e.t;f=e[d-1];if(0!=f){var k=f*(1<<this.F1)+(1<d?e[d-2]>>this.F2:0),l=this.FV/k,k=(1<<this.F1)/k,p=1<<this.F2,n=c.t,q=n-d,m=null==b?nbi():b;e.dlShiftTo(q,m);0<=c.compareTo(m)&&(c[c.t++]=1,c.subTo(m,c));BigInteger.ONE.dlShiftTo(d,
m);for(m.subTo(e,e);e.t<d;)e[e.t++]=0;for(;0<=--q;){var r=c[--n]==f?this.DM:Math.floor(c[n]*l+(c[n-1]+p)*k);if((c[n]+=e.am(0,r,c,q,0,d))<r){e.dlShiftTo(q,m);for(c.subTo(m,c);c[n]<--r;)c.subTo(m,c)}}null!=b&&(c.drShiftTo(d,b),g!=a&&BigInteger.ZERO.subTo(b,b));c.t=d;c.clamp();0<h&&c.rShiftTo(h,c);0>g&&BigInteger.ZERO.subTo(c,c)}}}}function bnMod(a){var b=nbi();this.abs().divRemTo(a,null,b);0>this.s&&0<b.compareTo(BigInteger.ZERO)&&a.subTo(b,b);return b}function Classic(a){this.m=a}
function cConvert(a){return 0>a.s||0<=a.compareTo(this.m)?a.mod(this.m):a}function cRevert(a){return a}function cReduce(a){a.divRemTo(this.m,null,a)}function cMulTo(a,b,c){a.multiplyTo(b,c);this.reduce(c)}function cSqrTo(a,b){a.squareTo(b);this.reduce(b)}Classic.prototype.convert=cConvert;Classic.prototype.revert=cRevert;Classic.prototype.reduce=cReduce;Classic.prototype.mulTo=cMulTo;Classic.prototype.sqrTo=cSqrTo;
function bnpInvDigit(){if(1>this.t)return 0;var a=this[0];if(0==(a&1))return 0;var b=a&3,b=b*(2-(a&15)*b)&15,b=b*(2-(a&255)*b)&255,b=b*(2-((a&65535)*b&65535))&65535,b=b*(2-a*b%this.DV)%this.DV;return 0<b?this.DV-b:-b}function Montgomery(a){this.m=a;this.mp=a.invDigit();this.mpl=this.mp&32767;this.mph=this.mp>>15;this.um=(1<<a.DB-15)-1;this.mt2=2*a.t}
function montConvert(a){var b=nbi();a.abs().dlShiftTo(this.m.t,b);b.divRemTo(this.m,null,b);0>a.s&&0<b.compareTo(BigInteger.ZERO)&&this.m.subTo(b,b);return b}function montRevert(a){var b=nbi();a.copyTo(b);this.reduce(b);return b}
function montReduce(a){for(;a.t<=this.mt2;)a[a.t++]=0;for(var b=0;b<this.m.t;++b){var c=a[b]&32767,d=c*this.mpl+((c*this.mph+(a[b]>>15)*this.mpl&this.um)<<15)&a.DM,c=b+this.m.t;for(a[c]+=this.m.am(0,d,a,b,0,this.m.t);a[c]>=a.DV;)a[c]-=a.DV,a[++c]++}a.clamp();a.drShiftTo(this.m.t,a);0<=a.compareTo(this.m)&&a.subTo(this.m,a)}function montSqrTo(a,b){a.squareTo(b);this.reduce(b)}function montMulTo(a,b,c){a.multiplyTo(b,c);this.reduce(c)}Montgomery.prototype.convert=montConvert;
Montgomery.prototype.revert=montRevert;Montgomery.prototype.reduce=montReduce;Montgomery.prototype.mulTo=montMulTo;Montgomery.prototype.sqrTo=montSqrTo;function bnpIsEven(){return 0==(0<this.t?this[0]&1:this.s)}function bnpExp(a,b){if(4294967295<a||1>a)return BigInteger.ONE;var c=nbi(),d=nbi(),f=b.convert(this),e=nbits(a)-1;for(f.copyTo(c);0<=--e;)if(b.sqrTo(c,d),0<(a&1<<e))b.mulTo(d,f,c);else var g=c,c=d,d=g;return b.revert(c)}
function bnModPowInt(a,b){var c;c=256>a||b.isEven()?new Classic(b):new Montgomery(b);return this.exp(a,c)}BigInteger.prototype.copyTo=bnpCopyTo;BigInteger.prototype.fromInt=bnpFromInt;BigInteger.prototype.fromString=bnpFromString;BigInteger.prototype.clamp=bnpClamp;BigInteger.prototype.dlShiftTo=bnpDLShiftTo;BigInteger.prototype.drShiftTo=bnpDRShiftTo;BigInteger.prototype.lShiftTo=bnpLShiftTo;BigInteger.prototype.rShiftTo=bnpRShiftTo;BigInteger.prototype.subTo=bnpSubTo;
BigInteger.prototype.multiplyTo=bnpMultiplyTo;BigInteger.prototype.squareTo=bnpSquareTo;BigInteger.prototype.divRemTo=bnpDivRemTo;BigInteger.prototype.invDigit=bnpInvDigit;BigInteger.prototype.isEven=bnpIsEven;BigInteger.prototype.exp=bnpExp;BigInteger.prototype.toString=bnToString;BigInteger.prototype.negate=bnNegate;BigInteger.prototype.abs=bnAbs;BigInteger.prototype.compareTo=bnCompareTo;BigInteger.prototype.bitLength=bnBitLength;BigInteger.prototype.mod=bnMod;BigInteger.prototype.modPowInt=bnModPowInt;
BigInteger.ZERO=nbv(0);BigInteger.ONE=nbv(1);function Arcfour(){this.j=this.i=0;this.S=[]}function ARC4init(a){var b,c,d;for(b=0;256>b;++b)this.S[b]=b;for(b=c=0;256>b;++b)c=c+this.S[b]+a[b%a.length]&255,d=this.S[b],this.S[b]=this.S[c],this.S[c]=d;this.j=this.i=0}function ARC4next(){var a;this.i=this.i+1&255;this.j=this.j+this.S[this.i]&255;a=this.S[this.i];this.S[this.i]=this.S[this.j];this.S[this.j]=a;return this.S[a+this.S[this.i]&255]}Arcfour.prototype.init=ARC4init;Arcfour.prototype.next=ARC4next;
function prng_newstate(){return new Arcfour}var rng_psize=256,rng_state,rng_pool,rng_pptr;function rng_seed_int(a){rng_pool[rng_pptr++]^=a&255;rng_pool[rng_pptr++]^=a>>8&255;rng_pool[rng_pptr++]^=a>>16&255;rng_pool[rng_pptr++]^=a>>24&255;rng_pptr>=rng_psize&&(rng_pptr-=rng_psize)}function rng_seed_time(){rng_seed_int((new Date).getTime())}
if(null==rng_pool){rng_pool=[];rng_pptr=0;var t;if("Netscape"==navigator.appName&&"5">navigator.appVersion&&window.crypto){var z=window.crypto.random(32);for(t=0;t<z.length;++t)rng_pool[rng_pptr++]=z.charCodeAt(t)&255}for(;rng_pptr<rng_psize;)t=Math.floor(65536*Math.random()),rng_pool[rng_pptr++]=t>>>8,rng_pool[rng_pptr++]=t&255;rng_pptr=0;rng_seed_time()}
function rng_get_byte(){if(null==rng_state){rng_seed_time();rng_state=prng_newstate();rng_state.init(rng_pool);for(rng_pptr=0;rng_pptr<rng_pool.length;++rng_pptr)rng_pool[rng_pptr]=0;rng_pptr=0}return rng_state.next()}function rng_get_bytes(a){var b;for(b=0;b<a.length;++b)a[b]=rng_get_byte()}function SecureRandom(){}SecureRandom.prototype.nextBytes=rng_get_bytes;function parseBigInt(a,b){return new BigInteger(a,b)}
function pkcs1pad2(a,b){if(b<a.length+11)return null;for(var c=[],d=a.length-1;0<=d&&0<b;){var f=a.charCodeAt(d--);128>f?c[--b]=f:127<f&&2048>f?(c[--b]=f&63|128,c[--b]=f>>6|192):(c[--b]=f&63|128,c[--b]=f>>6&63|128,c[--b]=f>>12|224)}c[--b]=0;d=new SecureRandom;for(f=[];2<b;){for(f[0]=0;0==f[0];)d.nextBytes(f);c[--b]=f[0]}c[--b]=2;c[--b]=0;return new BigInteger(c)}function RSAKey(){this.n=null;this.e=0;this.coeff=this.dmq1=this.dmp1=this.q=this.p=this.d=null}
function RSASetPublic(a,b){null!=a&&(null!=b&&0<a.length&&0<b.length)&&(this.n=parseBigInt(a,16),this.e=parseInt(b,16))}function RSADoPublic(a){return a.modPowInt(this.e,this.n)}function RSAEncrypt(a){a=pkcs1pad2(a,this.n.bitLength()+7>>3);if(null==a)return null;a=this.doPublic(a);if(null==a)return null;a=a.toString(16);return 0==(a.length&1)?a:"0"+a}RSAKey.prototype.doPublic=RSADoPublic;RSAKey.prototype.setPublic=RSASetPublic;RSAKey.prototype.encrypt=RSAEncrypt;
var json_parse=function(){var a,b,c={'"':'"',"\\":"\\","/":"/",b:"\b",f:"\f",n:"\n",r:"\r",t:"\t"},d,f=function(b){throw{name:"SyntaxError",message:b,at:a,text:d};},e=function(c){c&&c!==b&&f("Expected '"+c+"' instead of '"+b+"'");b=d.charAt(a);a+=1;return b},g=function(){var a;a="";"-"===b&&(a="-",e("-"));for(;"0"<=b&&"9">=b;)a+=b,e();if("."===b)for(a+=".";e()&&"0"<=b&&"9">=b;)a+=b;if("e"===b||"E"===b){a+=b;e();if("-"===b||"+"===b)a+=b,e();for(;"0"<=b&&"9">=b;)a+=b,e()}a=+a;if(isFinite(a))return a;
f("Bad number")},h=function(){var a,d,g="",h;if('"'===b)for(;e();){if('"'===b)return e(),g;if("\\"===b)if(e(),"u"===b){for(d=h=0;4>d;d+=1){a=parseInt(e(),16);if(!isFinite(a))break;h=16*h+a}g+=String.fromCharCode(h)}else if("string"===typeof c[b])g+=c[b];else break;else g+=b}f("Bad string")},k=function(){for(;b&&" ">=b;)e()},l=function(){switch(b){case "t":return e("t"),e("r"),e("u"),e("e"),!0;case "f":return e("f"),e("a"),e("l"),e("s"),e("e"),!1;case "n":return e("n"),e("u"),e("l"),e("l"),null}f("Unexpected '"+
b+"'")},p;p=function(){k();switch(b){case "{":var a;a:{var c={};if("{"===b){e("{");k();if("}"===b){e("}");a=c;break a}for(;b;){a=h();k();e(":");Object.hasOwnProperty.call(c,a)&&f('Duplicate key "'+a+'"');c[a]=p();k();if("}"===b){e("}");a=c;break a}e(",");k()}}f("Bad object");a=void 0}return a;case "[":a:{a=[];if("["===b){e("[");k();if("]"===b){e("]");break a}for(;b;){a.push(p());k();if("]"===b){e("]");break a}e(",");k()}}f("Bad array");a=void 0}return a;case '"':return h();case "-":return g();default:return"0"<=
b&&"9">=b?g():l()}};return function(c,e){var g;d=c;a=0;b=" ";g=p();k();b&&f("Syntax error");return"function"===typeof e?function s(a,b){var c,d,f=a[b];if(f&&"object"===typeof f)for(c in f)Object.prototype.hasOwnProperty.call(f,c)&&(d=s(f,c),void 0!==d?f[c]=d:delete f[c]);return e.call(a,b,f)}({"":g},""):g}}();function _key(a,b){window._key_n=a;window._key_e=b}
function _encode(a){var b="";if("string"===typeof a)b=a;else{var c=encodeURIComponent,d;for(d in a)a.hasOwnProperty(d)&&(b+="\x26"+c(d)+"\x3d"+c(a[d]))}return b}function make_XMLHttpRequest(){if(window.XMLHttpRequest)return new window.XMLHttpRequest;try{return new window.ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(a){return new window.ActiveXObject("Microsoft.XMLHTTP")}}function showProgressIcon(){document.getElementById("progress").style.display="block"}
function hideProgressIcon(){document.getElementById("progress").style.display="none"}function disableIndicator(){document.getElementById("indicator").removeAttribute("class")}function storeElemValue(a,b){var c=document.getElementById(a);c&&(b[a]=c.value)}
function sendLoginRequestToBI(){var a=document.getElementById("password").value,b=new RSAKey;b.setPublic(window._key_n,window._key_e);a={password:b.encrypt(a)};storeElemValue("nik",a);storeElemValue("paybylink_qs",a);storeElemValue("paybylink_mac",a);new Ajax("login",endLogin,_encode(a))}function startLogin(){showProgressIcon();sendLoginRequestToBI()}
function endLogin(a,b){var c,d,f,e;if(200===a){try{e=json_parse(b)}catch(g){e=void 0}if(e){if("OK"===e.status){disableIndicator();redirectToBI(e.redirect);return}c=e.message;d=e.systemError;f=e.migrateError}}d?showErrorMessage(d,"message-label"):c?setLoginFailedStatus(c):f&&showErrorView("login-top",f,"to_migrate_login_button");hideProgressIcon();clearInput("password")}function clearInput(a){document.getElementById(a).value=""}
function setLoginFailedStatus(a){a||(a="Podano nieprawidłowe hasło lub login");showErrorMessage(a,"message-label")}function showErrorMessage(a,b){var c=document.getElementById(b);c.style.display="block";c.innerHTML=a;c.onclick=hideErrorMessage;var d=document.getElementById("text-check");d.innerHTML=a;d.style.fontSize=c.style.fontSize;d.clientWidth+1>c.clientWidth||-1<a.indexOf("\x3cbr")?(c.style.height="40px",c.style.paddingTop="10px"):(c.style.height="35px",c.style.paddingTop="15px")}
function hideErrorMessage(){document.getElementById("message-label").style.display="none"}function redirectToBI(a){document.location.href=document.location.protocol+"//"+document.location.host+a}
function Ajax(a,b,c){this.bindFunction=function(a,b){return function(){return a.apply(b,[b])}};this.stateChange=function(a){a=this.request;4===a.readyState&&this.callbackFunction(a.status,a.responseText)};this.postBody=c||"";this.callbackFunction=b;if(this.request=make_XMLHttpRequest())b=this.request,b.onreadystatechange=this.bindFunction(this.stateChange,this),""===this.postBody?b.open("GET",a,!0):(b.open("POST",a,!0),b.setRequestHeader("X-Requested-With","XMLHttpRequest"),b.setRequestHeader("Content-type",
"application/x-www-form-urlencoded")),b.send(this.postBody)}function changeLang(a){setCookie("lang",a,365);window.location.reload()}function showActiveLang(){var a=getCookie("lang");if(a&&(a=2<a.length?a.substr(0,2):a,a=document.getElementById("ico-"+a))){a.className="";return}a=getQueryParams(document.location.search);if(a.lang&&(a=document.getElementById("ico-"+a.lang))){a.className="";return}document.getElementById("ico-pl").className=""}
function getQueryParams(a){a=a.split("+").join(" ");for(var b={},c,d=/[?&]?([^=]+)=([^&]*)/g;c=d.exec(a);)b[decodeURIComponent(c[1])]=decodeURIComponent(c[2]);return b}
function _init(){var a=document.getElementById("login_button"),b=document.getElementById("nik"),c=document.getElementById("password");a.onclick=startLogin;b.value="";a.onkeypress=keyPressed;b.onkeypress=keyPressed;c.onkeypress=keyPressed;assignMigrateLink();assignConfirmBtn();assignCancelBtn();assignCodeConfirmBtn();assignOKBtn();assignToLoginBtn();assignToMigrateLoginBtn();assignMigrateNikLbl();assignMigratePhoneLbl();assignOneTimeCodeLbl();showActiveLang();b.focus()}
function keyPressed(a){a||(a=window.event);return 13==a.keyCode?(startLogin(),!1):!0}function _seed(){rng_seed_time()}function getInternetExplorerVersion(){var a=window.navigator.userAgent,b=a.indexOf("MSIE "),c=a.indexOf("Trident/");return 0<b?parseInt(a.substring(b+5,a.indexOf(".",b)),10):0<c?(b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10)):-1}function checkVersion(){var a=getInternetExplorerVersion();-1<a&&11>a&&makePlaceholders()}
function makePlaceholders(){var a=document.getElementById("nik"),b=document.getElementById("password"),c=document.getElementById("nik-migrate"),d=document.getElementById("placeholder-for-nik"),f=document.getElementById("placeholder-for-pass"),e=document.getElementById("placeholder-for-migrate-nik");d.style.display="inline";f.style.display="inline";a.placeholder="";b.placeholder="";a.attachEvent?(a.attachEvent("onfocus",onFocus),a.attachEvent("onblur",onBlur),a.attachEvent("onpropertychange",onChange)):
a.addEventListener&&(a.addEventListener("focus",onFocus,!1),a.addEventListener("blur",onBlur,!1),a.addEventListener("propertychange",onChange,!1));b.attachEvent?(b.attachEvent("onfocus",onFocus),b.attachEvent("onblur",onBlur),b.attachEvent("onpropertychange",onChange)):b.addEventListener&&(b.addEventListener("focus",onFocus,!1),b.addEventListener("blur",onBlur,!1),b.addEventListener("propertychange",onChange,!1));c.attachEvent?(c.attachEvent("onfocus",onFocus),c.attachEvent("onblur",onBlur),c.attachEvent("onpropertychange",
onChange)):c.addEventListener&&(c.addEventListener("focus",onFocus,!1),c.addEventListener("blur",onBlur,!1),c.addEventListener("propertychange",onChange,!1));d.attachEvent?d.attachEvent("onclick",function(){a.focus()}):d.addEventListener&&d.addEventListener("click",function(){a.focus()},!1);f.attachEvent?f.attachEvent("onclick",function(){b.focus()}):f.addEventListener&&f.addEventListener("click",function(){b.focus()},!1);e.attachEvent?e.attachEvent("onclick",function(){c.focus()}):e.addEventListener&&
e.addEventListener("click",function(){c.focus()},!1)}function onFocus(){onFocusForInput("nik","placeholder-for-nik");onFocusForInput("password","placeholder-for-pass");onFocusForInput("nik-migrate","placeholder-for-migrate-nik")}function onBlur(){onBlurForInput("nik","placeholder-for-nik");onBlurForInput("password","placeholder-for-pass");onBlurForInput("nik-migrate","placeholder-for-migrate-nik")}
function onChange(){onFocusForInput("nik","placeholder-for-nik");onFocusForInput("password","placeholder-for-pass");onFocusForInput("nik-migrate","placeholder-for-migrate-nik")}function onFocusForInput(a,b){var c=document.getElementById(a),d=document.getElementById(b);""!=c.value&&(d.style.display="none")}function onBlurForInput(a,b){var c=document.getElementById(a),d=document.getElementById(b);""==c.value&&(d.style.display="inline")}window._init=_init;window._seed=_seed;window._key=_key;
function setCookie(a,b,c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires\x3d"+d.toGMTString();document.cookie=a+"\x3d"+b+c+"; path\x3d/"}function getCookie(a){a+="\x3d";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}
function checkCookies(){if("yes"!=getCookie("cookiesAccepted")){var a=document.createElement("div");a.id="cookiePopup";var b='\x3cdiv id\x3d"cookies-required-message"\x3eW ramach naszej witryny stosujemy pliki cookies. Korzystanie z witryny bez zmiany ustawień przeglądarki oznacza, że akceptują Państwo otrzymywanie cookies. W dowolnej chwili możecie Państwo dokonać zmiany ustawień dotyczących plików cookies. Więcej informacji o \x3ca href\x3d"'+(-1!=window.location.href.indexOf("biz")?"http://www.bizbank.pl/polityka-prywatnosci/":
"http://www.banksmart.pl/o-nas/polityka-prywatnosci.html")+'" target\x3d"_blank" style\x3d"text-decoration:none;" \x3epolityce prywatności\x3c/a\x3e.\x3ca href\x3d"javascript:closeWindow();" id\x3d"accept-cookies-button" \x3eZamknij\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;document.body.appendChild(a)}}function closeWindow(){setCookie("cookiesAccepted","yes",700);document.getElementById("cookiePopup").removeChild(document.getElementById("cookies-required-message"))}
function hideElement(a){a=document.getElementById(a);"undefined"!=typeof a&&null!=a&&(a.style.display="none")}function showElement(a,b){var c=document.getElementById(a);"undefined"!=typeof c&&null!=c&&(c.style.display=b)}function clearMigrateFields(){document.getElementById("nik-migrate").value="";document.getElementById("phone").value="";document.getElementById("regulation").checked=!1}
function showPlaceHoldersForIE(){var a=getInternetExplorerVersion();-1<a&&11>a&&(a=document.getElementById("nik-migrate"),document.getElementById("placeholder-for-migrate-nik").style.display="inline",a.placeholder="")}function hideAllTopElements(){hideElement("login-top");hideElement("migrate-login-top");hideElement("migrate-pass-top");hideElement("migrate-error-top")}function buttonKeyPressedCallback(a){a||(a=window.event);return 13==a.keyCode?(a.target.onclick.call(a.target),!1):!0}
function labelKeyPressedCallback(a){a||(a=window.event);return 13==a.keyCode&&"undefined"!=typeof a.target&&null!=a.target?(a=a.target.getAttribute("id"),"nik-migrate"===a||"phone"===a?confirmPhoneNumber():"one-time-code"===a&&confirmCode(),!1):!0}function showMigrateLoginForm(){showProgressIcon();hideElement("migrate-message-label");hideAllTopElements();showElement("migrate-login-top","block");clearMigrateFields();showPlaceHoldersForIE();hideProgressIcon()}
function showLoginForm(){showProgressIcon();hideElement("migrate-message-label");hideElement("message-label");hideAllTopElements();showElement("login-top","block");clearInput("nik");clearInput("password");hideProgressIcon()}function showMigratePassForm(){showProgressIcon();hideElement("migrate-message-label");hideAllTopElements();showElement("migrate-pass-top","block");clearInput("one-time-code");hideProgressIcon()}
function showErrorView(a,b,c){showProgressIcon();hideElement(a);showElement("migrate-error-top","block");document.getElementById("migrate-error").innerHTML=b;hideElement("ok_button");hideElement("to_login_button");hideElement("to_migrate_login_button");"ok_button"==c?showElement("ok_button","inline"):"to_login_button"==c?showElement("to_login_button","inline"):"to_migrate_login_button"==c&&showElement("to_migrate_login_button","inline");hideProgressIcon()}
function returnToMigrateLoginForm(){showProgressIcon();hideElement("migrate-message-label");hideAllTopElements();showElement("migrate-login-top","block");clearMigrateFields();showPlaceHoldersForIE();hideProgressIcon()}function getRegulationLink(){showProgressIcon();new Ajax("login",confirmRegulationLinkCallback,_encode({"regulation-link":!0}))}
function confirmRegulationLinkCallback(a,b){var c;if(200===a){try{c=json_parse(b)}catch(d){c=void 0}if(c&&"OK"===c.status){c=c.message;var f=document.getElementById("regulation-link");f&&(f.href=c)}}showMigrateLoginForm()}
function confirmPhoneNumber(){showProgressIcon();hideElement("migrate-message-label");var a={migrate:!0};storeElemValue("nik-migrate",a);storeElemValue("phone",a);var b=document.getElementById("regulation");b&&(a.regulation=b.checked);new Ajax("login",confirmPhoneNumberCallback,_encode(a))}
function confirmPhoneNumberCallback(a,b){var c,d,f,e,g;if(200===a){try{g=json_parse(b)}catch(h){g=void 0}if(g)if("OK"!==g.status)f=g.message,e=g.systemError,c=g.validationMessage,d=g.verificationMessage;else{showMigratePassForm();return}}f?showErrorMessage(f,"migrate-message-label"):e?showErrorMessage(e,"migrate-message-label"):c?showErrorMessage(c,"migrate-message-label"):d&&showErrorView("migrate-login-top",d,"to_login_button");hideProgressIcon()}
function confirmCode(){showProgressIcon();hideElement("migrate-message-label");var a=document.getElementById("nik-migrate").value,b=document.getElementById("one-time-code").value,c=new RSAKey;c.setPublic(window._key_n,window._key_e);a={"migrate-login":!0,password:c.encrypt(b),nik:a};new Ajax("login",confirmCodeCallback,_encode(a))}
function confirmCodeCallback(a,b){var c,d,f;if(200===a){try{f=json_parse(b)}catch(e){f=void 0}if(f)if("OK"!==f.status)c=f.message,d=f.systemError;else{disableIndicator();redirectToBI(f.redirect);return}}d?showErrorView("migrate-pass-top",d,"ok_button"):c&&showErrorView("migrate-pass-top",c,"ok_button");hideProgressIcon();clearInput("one-time-code")}
function assignMigrateLink(){var a=document.getElementById("migrate_client_link");"undefined"!=typeof a&&null!=a&&(a.onclick=getRegulationLink,a.onkeypress=buttonKeyPressedCallback)}function assignConfirmBtn(){var a=document.getElementById("confirm_button");"undefined"!=typeof a&&null!=a&&(a.onclick=confirmPhoneNumber,a.onkeypress=buttonKeyPressedCallback)}
function assignCancelBtn(){var a=document.getElementById("cancel_button");"undefined"!=typeof a&&null!=a&&(a.onclick=showLoginForm,a.onkeypress=buttonKeyPressedCallback)}function assignCodeConfirmBtn(){var a=document.getElementById("confirm_code_button");"undefined"!=typeof a&&null!=a&&(a.onclick=confirmCode,a.onkeypress=buttonKeyPressedCallback)}
function assignOKBtn(){var a=document.getElementById("ok_button");"undefined"!=typeof a&&null!=a&&(a.onclick=returnToMigrateLoginForm,a.onkeypress=buttonKeyPressedCallback)}function assignToLoginBtn(){var a=document.getElementById("to_login_button");"undefined"!=typeof a&&null!=a&&(a.onclick=showLoginForm,a.onkeypress=buttonKeyPressedCallback)}
function assignToMigrateLoginBtn(){var a=document.getElementById("to_migrate_login_button");"undefined"!=typeof a&&null!=a&&(a.onclick=showMigrateLoginForm,a.onkeypress=buttonKeyPressedCallback)}function assignMigrateNikLbl(){var a=document.getElementById("nik-migrate");"undefined"!=typeof a&&null!=a&&(a.onkeypress=labelKeyPressedCallback)}function assignMigratePhoneLbl(){var a=document.getElementById("phone");"undefined"!=typeof a&&null!=a&&(a.onkeypress=labelKeyPressedCallback)}
function assignOneTimeCodeLbl(){var a=document.getElementById("one-time-code");"undefined"!=typeof a&&null!=a&&(a.onkeypress=labelKeyPressedCallback)};
